*** Variables ***
${INPUT_USERNAME}    //input[@name="username"]
${INPUT_PASSWORD}    //input[@name="password"]
${BUTTON_SUBMIT}     //button[@type="submit"]
${USERNAME_WRONG}    //*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[1]/div/span
${PASSWORD_WRONG}    //*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/form/div[2]/div/span
${INVALID}    //*[@id="app"]/div[1]/div/div[1]/div/div[2]/div[2]/div/div[1]/div[1]
